C:/Users/User/Dropbox/UFSC/2018.2/OO/Projeto_Final/fw/src/LCD_NHDC12864.h File Reference
Implements the drivers of the LCD NHDC1264.
Macros
#define LCD_A0 GPIO_PIN_5
#define COMP_LCD_CONFIG_VECTOR 11	/**Config vector length*/
#define LCD_ON 0xAF
Functions
void LCDInitializeNHDC12864 (void)
LCD initialization.
void LCDWrite (char mode, char data)
Function to write data and commands in the LCD.
void LCDSetStartLine (char addr)
Function to read data rom the LCD.
void LCDSetColumn (char addr)
Function to set the column to write.
void LCDSetPage (char addr)
Function to set the page to write.
void LCDClear (void)
Function to clear the entire LCD.
void LCDReverseBlink (char nBlink)
Function to blink the LCD a number of times.
void LCDWriteChar7x8 (const char *alphabet, char letter)
Function to write a char in the LCD.
void LCDWriteString (const char *alphabet, char *str)
Function to write a string in the LCD.
Variables
const char times8 [95 *7]
Detailed Description
Implements the drivers of the LCD NHDC1264.
Version
1.0
Author
Kleber Gouveia
Date
Nov 27, 2018
Module Name: LCD_NHDC12864.h
References
NHDC1264 Datasheet
Revisions
Revision: 1.0 27-Nov-2018 Kleber Gouveia
Working baseline.
Macro Definition Documentation
COMP_LCD_CONFIG_VECTOR
#define COMP_LCD_CONFIG_VECTOR 11	/**Config vector length*/
LCD driver configurations
Definition at line 46 of file LCD_NHDC12864.h.
LCD_A0
#define LCD_A0 GPIO_PIN_5
LCD Pin mapping
Definition at line 33 of file LCD_NHDC12864.h.
LCD_ON
#define LCD_ON 0xAF
LCD NHD-C12864B2Z commands
Definition at line 57 of file LCD_NHDC12864.h.
Function Documentation
LCDClear()
void LCDClear (void)
Function to clear the entire LCD.
Parameters
none
Returns
none
Definition at line 305 of file LCD_NHDC12864.c.
References LCDSetColumn(), and LCDSetPage().
Referenced by CLCD::clearScreen().
LCDInitializeNHDC12864()
void LCDInitializeNHDC12864 (void)
LCD initialization.
Parameters
none
Returns
none
Definition at line 148 of file LCD_NHDC12864.c.
LCDReverseBlink()
void LCDReverseBlink (char nBlink)
Function to blink the LCD a number of times.
Parameters
nBlink - number of times to blink
Returns
none
Definition at line 329 of file LCD_NHDC12864.c.
References LCDWrite().
LCDSetColumn()
void LCDSetColumn (char addr)
Function to set the column to write.
Parameters
addr the position selected
Returns
none
Definition at line 284 of file LCD_NHDC12864.c.
References LCDWrite().
Referenced by LCDClear(), LCDWriteString(), and CLCD::setPosition().
LCDSetPage()
void LCDSetPage (char addr)
Function to set the page to write.
Parameters
addr the position selected
Returns
none
Definition at line 295 of file LCD_NHDC12864.c.
References LCDWrite().
Referenced by LCDClear(), LCDWriteString(), and CLCD::setPosition().
LCDSetStartLine()
void LCDSetStartLine (char addr)
Function to read data rom the LCD.
Parameters
mode can be DATA or COMM
Returns
value read Function to set the line to write
Parameters
addr the position selected
Returns
none
Definition at line 274 of file LCD_NHDC12864.c.
References LCDWrite().
LCDWrite()
void LCDWrite (char mode, char data)
Function to write data and commands in the LCD.
Parameters
mode can be DATA or COMM
data the information to be sent
Returns
none
Definition at line 169 of file LCD_NHDC12864.c.
Referenced by LCDReverseBlink(), LCDSetColumn(), LCDSetPage(), LCDSetStartLine(), and LCDWriteChar7x8().
LCDWriteChar7x8()
void LCDWriteChar7x8 (const char * alphabet, char letter)
Function to write a char in the LCD.
Parameters
*alphabet - pointer to the font tipe selected
letter - the char to write
Returns
none
Definition at line 349 of file LCD_NHDC12864.c.
References LCDWrite().
Referenced by LCDWriteString().
LCDWriteString()
void LCDWriteString (const char * alphabet, char * str)
Function to write a string in the LCD.
Parameters
*alphabet - pointer to the font tipe selected
*str - pointer to the string to write
Returns
none
Definition at line 365 of file LCD_NHDC12864.c.
References LCDSetColumn(), LCDSetPage(), and LCDWriteChar7x8().
Referenced by CLCD::writeString().
Variable Documentation
times8
const char times8[95 *7]
LCD display ON/OFF: ON
 Lookup Table containing printed characteres 7x8 (between ` ` and `~`),Times New Human, ASCII.
Definition at line 45 of file LCD_NHDC12864.c.
Referenced by CLCD::writeString().