CControl Class Reference
CControl class implementation.
#include <CONTROL.h>
Public Member Functions
CControl ()
GPIO constructor. This method create a CCONTROL object instance.
~CControl ()
Class destructor.
void messageManager (void)
This method coordinate timming and priorites of the messages to be shown at the display considering the priorities as FSM actions > Date/Time information > advertising.
void receiveCommand (void)
Method to receive a command from console and put it in the queue to be parsed.
void commandsParser (void)
Method parser the commands received from the commands queue.
Detailed Description
CControl class implementation.
This class implements the methods to manager the messages and the commands of the system.
Definition at line 50 of file CONTROL.h.
Member Function Documentation
commandsParser()
void CControl::commandsParser (void)
Method parser the commands received from the commands queue.
Parameters
none
Returns
none
Definition at line 142 of file CONTROL.cpp.
References Cqueue< T >::getSize(), Cqueue< T >::popFront(), Cqueue< T >::pushBack(), and CConsole::writeLogString().
messageManager()
void CControl::messageManager (void)
This method coordinate timming and priorites of the messages to be shown at the display considering the priorities as FSM actions > Date/Time information > advertising.
Parameters
none
Returns
none
Definition at line 54 of file CONTROL.cpp.
References Cqueue< T >::checkEmpty().
receiveCommand()
void CControl::receiveCommand (void)
Method to receive a command from console and put it in the queue to be parsed.
Parameters
none
Returns
none
Definition at line 127 of file CONTROL.cpp.
References Cqueue< T >::pushBack(), and CConsole::ReadCommand().
The documentation for this class was generated from the following files:
C:/Users/User/Dropbox/UFSC/2018.2/OO/Projeto_Final/fw/src/CONTROL.h
C:/Users/User/Dropbox/UFSC/2018.2/OO/Projeto_Final/fw/src/CONTROL.cpp