CLCD Class Reference
CLCD class implementation.
#include <LCD_UC.h>
Public Member Functions
CLCD ()
Class constructor.
~CLCD ()
Class destructor.
void clearScreen ()
Method to clear the entire LCD.
void writeString (string str)
Method to write a string in the LCD.
void writeInteger (int num)
Method to write a number in the LCD.
void setPosition (int x, int y)
Method to the position to write in LCD.
Detailed Description
CLCD class implementation.
This class implements the methods to initialize and access the LCD from the microcontroller's GPIO.
This class implements the methods to initialize and access the LCD from the PC's.
Definition at line 32 of file LCD_UC.h.
Member Function Documentation
clearScreen()
void CLCD::clearScreen () [virtual]
Method to clear the entire LCD.
Parameters
none
Returns
none
Implements CDisplay.
Definition at line 81 of file LCD_UC.cpp.
References LCDClear().
setPosition()
void CLCD::setPosition (int x, int y) [virtual]
Method to the position to write in LCD.
Parameters
x - is the column
y - is the page
Returns
none
Implements CDisplay.
Definition at line 116 of file LCD_UC.cpp.
References LCDSetColumn(), and LCDSetPage().
writeInteger()
void CLCD::writeInteger (int num) [virtual]
Method to write a number in the LCD.
Parameters
num - number to write
Returns
none
Implements CDisplay.
Definition at line 105 of file LCD_UC.cpp.
writeString()
void CLCD::writeString (string str) [virtual]
Method to write a string in the LCD.
Parameters
str - string to write
Returns
none
Implements CDisplay.
Definition at line 92 of file LCD_UC.cpp.
References LCDWriteString(), and times8.
The documentation for this class was generated from the following files:
C:/Users/User/Dropbox/UFSC/2018.2/OO/Projeto_Final/fw/src/LCD_UC.h
C:/Users/User/Dropbox/UFSC/2018.2/OO/Projeto_Final/fw/src/SCREEN_PC.h
C:/Users/User/Dropbox/UFSC/2018.2/OO/Projeto_Final/fw/src/LCD_UC.cpp
C:/Users/User/Dropbox/UFSC/2018.2/OO/Projeto_Final/fw/src/SCREEN_PC.cpp