Cqueue< T > Class Template Reference
Queue implementation with generic node.
#include <queue.hpp>
Public Member Functions
Cqueue ()
Class constructor.
~Cqueue ()
Class destructor.
bool checkEmpty ()
Method to check if the queue is empty.
int getSize ()
Method to obtain the number of nodes that a queue contains.
void pushBack (T)
Method to create a node to insert new data at the end of teh queue.
T popFront ()
Method to get the data from the queue and delete the node used to store it.
Detailed Description
template<class T>
class Cqueue< T >
Queue implementation with generic node.
This template class implements the methods to initialize and access queues with generic nodes.
Definition at line 33 of file queue.hpp.
Member Function Documentation
checkEmpty()
template<class T >
bool Cqueue< T >::checkEmpty ()
Method to check if the queue is empty.
Parameters
none
Returns
bool - TRUE if the queue is empty, FALSE if it isn't.
Definition at line 74 of file queue.hpp.
Referenced by CControl::messageManager().
getSize()
template<class T >
int Cqueue< T >::getSize ()
Method to obtain the number of nodes that a queue contains.
Parameters
none
Returns
int - number of nodes.
Definition at line 85 of file queue.hpp.
Referenced by CControl::commandsParser().
popFront()
template<class T >
T Cqueue< T >::popFront ()
Method to get the data from the queue and delete the node used to store it.
Parameters
none
Returns
T - generic data type information.
Definition at line 120 of file queue.hpp.
Referenced by CControl::commandsParser().
pushBack()
template<class T>
void Cqueue< T >::pushBack (T newData)
Method to create a node to insert new data at the end of teh queue.
Parameters
newData - Generic data type to be inserted at the queue.
Returns
none
Definition at line 96 of file queue.hpp.
Referenced by CControl::commandsParser(), and CControl::receiveCommand().
The documentation for this class was generated from the following file:
C:/Users/User/Dropbox/UFSC/2018.2/OO/Projeto_Final/fw/src/queue.hpp